### ISSUE TITLE
Archive repo

### ISSUE THREAD

**Issue by slook** [vasi/nicotine.app#1]
This is not needed any more, since the target macOS version is obsolete now and recent versions are natively supported by the main project:

https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/DOWNLOADS.md#macos

**Comment by mathiascode** [comment]
For historical purposes, I think deleting repositories is a bad idea, but the repo could be archived instead.

**Comment by vasi** [comment]
Wow, seriously? Repos don't cost you anything, if you don't like to see historical code, you can just not look at it.

**Comment by slook** [comment]
Sorry, it was not my intention to cause any offense. My concern was raised after stumbling upon this repo during a search for something else, it seemed that it could be possible for a macOS user to inadvertently install this instead of the proper version. The suggestion to archive the repo is obviously more appropriate than my original suggestion of deletion.
